name: CI

on:
  push:
    branches:
      - main
      - release
      - development
      - 'feature/*'
  pull_request:
    branches:
      - main
      - release
      - development
      - 'feature/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build, Lint and Test

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Configura Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Lint with flake8
        run: |
          echo "Running flake8 lint..."
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics

      - name: Run tests with pytest
        run: |
          echo "Running tests..."
          pytest -v --maxfail=1 --disable-warnings --tb=short
